<a href="https://colab.research.google.com/github/TrongAnh2210/Exercises-2/blob/main/Exercises2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive 
drive.mount("/content/gdrive", force_remount=True)

Mounted at /content/gdrive

# Mục mới

In [1]:
import pandas as pd
url = 'http://winterolympicsmedals.com/medals.csv'
data = pd.read_csv(url)
data

,Year,City,Sport,Discipline,NOC,Event,Event gender,Medal
0,1924,Chamonix,Skating,Figure skating,AUT,individual,M,Silver
1,1924,Chamonix,Skating,Figure skating,AUT,individual,W,Gold
2,1924,Chamonix,Skating,Figure skating,AUT,pairs,X,Gold
3,1924,Chamonix,Bobsleigh,Bobsleigh,BEL,four-man,M,Bronze
4,1924,Chamonix,Ice Hockey,Ice Hockey,CAN,ice hockey,M,Gold
...,...,...,...,...,...,...,...,...
2306,2006,Turin,Skiing,Snowboard,USA,Half-pipe,M,Silver
2307,2006,Turin,Skiing,Snowboard,USA,Half-pipe,W,Gold
2308,2006,Turin,Skiing,Snowboard,USA,Half-pipe,W,Silver
2309,2006,Turin,Skiing,Snowboard,USA,Snowboard Cross,M,Gold
2310,2006,Turin,Skiing,Snowboard,USA,Snowboard Cross,W,Silver

***Số huy chương Vàng của USA qua các năm ***

In [2]:
import pandas as pd
dataframe = pd.read_csv(url)
dataframe[(dataframe['NOC'] == 'USA')&(dataframe['Medal'] == 'Gold')].head(1000)

,Year,City,Sport,Discipline,NOC,Event,Event gender,Medal
47,1924,Chamonix,Skating,Speed skating,USA,500m,M,Gold
84,1928,St. Moritz,Bobsleigh,Bobsleigh,USA,five-man,M,Gold
86,1928,St. Moritz,Bobsleigh,Skeleton,USA,individual,M,Gold
120,1932,Lake Placid,Bobsleigh,Bobsleigh,USA,four-man,M,Gold
123,1932,Lake Placid,Bobsleigh,Bobsleigh,USA,two-man,M,Gold
...,...,...,...,...,...,...,...,...
2301,2006,Turin,Skiing,Alpine Skiing,USA,Alpine combined,M,Gold
2302,2006,Turin,Skiing,Alpine Skiing,USA,giant slalom,W,Gold
2305,2006,Turin,Skiing,Snowboard,USA,Half-pipe,M,Gold
2307,2006,Turin,Skiing,Snowboard,USA,Half-pipe,W,Gold
2309,2006,Turin,Skiing,Snowboard,USA,Snowboard Cross,M,Gold

### **Số huy chương bạc của USA qua các năm **

In [3]:
dataframe[(dataframe['NOC'] == 'USA')&(dataframe['Medal'] == 'Silver')].head(1000)

,Year,City,Sport,Discipline,NOC,Event,Event gender,Medal
45,1924,Chamonix,Ice Hockey,Ice Hockey,USA,ice hockey,M,Silver
46,1924,Chamonix,Skating,Figure skating,USA,individual,W,Silver
85,1928,St. Moritz,Bobsleigh,Bobsleigh,USA,five-man,M,Silver
87,1928,St. Moritz,Bobsleigh,Skeleton,USA,individual,M,Silver
121,1932,Lake Placid,Bobsleigh,Bobsleigh,USA,four-man,M,Silver
...,...,...,...,...,...,...,...,...
2296,2006,Turin,Skating,Speed skating,USA,1000m,M,Silver
2298,2006,Turin,Skating,Speed skating,USA,1500m,M,Silver
2306,2006,Turin,Skiing,Snowboard,USA,Half-pipe,M,Silver
2308,2006,Turin,Skiing,Snowboard,USA,Half-pipe,W,Silver
2310,2006,Turin,Skiing,Snowboard,USA,Snowboard Cross,W,Silver

### **Số huy chương đồng của USA qua các năm **

In [4]:
dataframe[(dataframe['NOC'] == 'USA')&(dataframe['Medal'] == 'Bronze')].head(1000)

,Year,City,Sport,Discipline,NOC,Event,Event gender,Medal
48,1924,Chamonix,Skiing,Ski Jumping,USA,K90 individual (70m),M,Bronze
88,1928,St. Moritz,Skating,Figure skating,USA,individual,W,Bronze
89,1928,St. Moritz,Skating,Speed skating,USA,500m,M,Bronze
122,1932,Lake Placid,Bobsleigh,Bobsleigh,USA,two-man,M,Bronze
125,1932,Lake Placid,Skating,Figure skating,USA,individual,W,Bronze
179,1936,Garmisch-Partenkirchen,Bobsleigh,Bobsleigh,USA,two-man,M,Bronze
181,1936,Garmisch-Partenkirchen,Ice Hockey,Ice Hockey,USA,ice hockey,M,Bronze
182,1936,Garmisch-Partenkirchen,Skating,Speed skating,USA,500m,M,Bronze
242,1948,St. Moritz,Bobsleigh,Bobsleigh,USA,four-man,M,Bronze
244,1948,St. Moritz,Bobsleigh,Bobsleigh,USA,two-man,M,Bronze
310,1952,Oslo,Skating,Figure skating,USA,individual,M,Bronze
383,1956,Cortina d'Ampezzo,Bobsleigh,Bobsleigh,USA,four-man,M,Bronze
385,1956,Cortina d'Ampezzo,Skating,Figure skating,USA,individual,M,Bronze
463,1960,Squaw Valley,Skating,Figure skating,USA,individual,W,Bronze
465,1960,Squaw Valley,Skating,Figure skating,USA,pairs,X,Bronze
467,1960,Squaw Valley,Skating,Speed skating,USA,500m,W,Bronze
568,1964,Innsbruck,Skating,Figure skating,USA,individual,M,Bronze
571,1964,Innsbruck,Skiing,Alpine Skiing,USA,slalom,M,Bronze
573,1964,Innsbruck,Skiing,Alpine Skiing,USA,slalom,W,Bronze
675,1968,Grenoble,Skating,Speed skating,USA,1000m,W,Bronze
778,1972,Sapporo,Skating,Figure skating,USA,individual,W,Bronze
779,1972,Sapporo,Skating,Speed skating,USA,1000m,W,Bronze
783,1972,Sapporo,Skiing,Alpine Skiing,USA,downhill,W,Bronze
886,1976,Innsbruck,Skating,Figure skating,USA,ice dancing,X,Bronze
889,1976,Innsbruck,Skating,Speed skating,USA,1000m,W,Bronze
892,1976,Innsbruck,Skating,Speed skating,USA,500m,M,Bronze
894,1976,Innsbruck,Skiing,Alpine Skiing,USA,downhill,W,Bronze
1000,1980,Lake Placid,Skating,Figure skating,USA,individual,M,Bronze
1006,1980,Lake Placid,Skating,Speed skating,USA,3000m,W,Bronze
1258,1988,Calgary,Skating,Figure skating,USA,individual,W,Bronze
1259,1988,Calgary,Skating,Figure skating,USA,pairs,X,Bronze
1260,1988,Calgary,Skating,Speed skating,USA,1000m,W,Bronze
1427,1992,Albertville,Skating,Figure skating,USA,individual,W,Bronze
1435,1992,Albertville,Skiing,Freestyle Ski.,USA,moguls,M,Bronze
1607,1994,Lillehammer,Skating,Short Track S.,USA,3000m relay,W,Bronze
1609,1994,Lillehammer,Skating,Short Track S.,USA,500m,W,Bronze
1813,1998,Nagano,Luge,Luge,USA,doubles,X,Bronze
1818,1998,Nagano,Skating,Speed skating,USA,1500m,W,Bronze
1823,1998,Nagano,Skiing,Snowboard,USA,Half-pipe,M,Bronze
1824,1998,Nagano,Skiing,Snowboard,USA,Half-pipe,W,Bronze
2025,2002,Salt Lake City,Bobsleigh,Bobsleigh,USA,four-man,M,Bronze
2033,2002,Salt Lake City,Luge,Luge,USA,doubles,X,Bronze
2035,2002,Salt Lake City,Skating,Figure skating,USA,individual,M,Bronze
2036,2002,Salt Lake City,Skating,Figure skating,USA,individual,W,Bronze
2040,2002,Salt Lake City,Skating,Short Track S.,USA,500m,M,Bronze
2041,2002,Salt Lake City,Skating,Speed skating,USA,1000m,M,Bronze
2042,2002,Salt Lake City,Skating,Speed skating,USA,1000m,W,Bronze
2045,2002,Salt Lake City,Skating,Speed skating,USA,1500m,W,Bronze
2047,2002,Salt Lake City,Skating,Speed skating,USA,500m,M,Bronze
2054,2002,Salt Lake City,Skiing,Snowboard,USA,Giant parallel slalom,M,Bronze
2055,2002,Salt Lake City,Skiing,Snowboard,USA,Half-pipe,M,Bronze
2287,2006,Turin,Curling,Curling,USA,curling,M,Bronze
2288,2006,Turin,Ice Hockey,Ice Hockey,USA,ice hockey,W,Bronze
2291,2006,Turin,Skating,Short Track S.,USA,1000m,M,Bronze
2292,2006,Turin,Skating,Short Track S.,USA,5000m relay,M,Bronze
2297,2006,Turin,Skating,Speed skating,USA,1500m,M,Bronze
2303,2006,Turin,Skiing,Freestyle Ski.,USA,moguls,M,Bronze
2304,2006,Turin,Skiing,Snowboard,USA,Giant parallel slalom,W,Bronze

### **Số huy chương theo từng bộ môn của USA**

In [5]:
fr = dataframe.groupby('Sport').count()
dataframe
frame = dataframe[(dataframe['NOC'] == 'USA')]
frame.groupby('Sport').count()

            Year  City  Discipline  NOC  Event  Event gender  Medal
Sport
Bobsleigh     24    24          24   24     24            24     24
Curling        1     1           1    1      1             1      1
Ice Hockey    12    12          12   12     12            12     12
Luge           4     4           4    4      4             4      4
Skating      118   118         118  118    118           118    118
Skiing        57    57          57   57     57            57     57